export const projects = [
    {
      id: 1,
      status: "audited",
      title: "Smart contract audit",
      priority: "Low",
      issueCount: 4,
      description: "SQL injection vulnerability in user profile update functionality allowing data exfiltration.",
      deadline: "17th - Aug - 2025",
      submitted: "17th - Aug - 2025",
      action: "Go to Project",
      logo: "/researcherIcon/avatar.svg",
    },
    {
      id: 2,
      status: "progress",
      title: "Platform migration",
      priority: "Medium",
      issueCount: 3,
      description: "Migration to new hosting service for improved performance and scalability.",
      deadline: "30th - Sep - 2025",
      submitted: "10th - Sep - 2025",
      action: "Edit Report",
      logo: "/researcherIcon/avatar.svg",
    },
    {
      id: 3,
      status: "progress",
      title: "User interface redesign",
      priority: "High",
      issueCount: 5,
      description: "Complete overhaul of the user interface to enhance user experience.",
      deadline: "22nd - Oct - 2025",
      submitted: "01st - Oct - 2025",
      action: "Edit Report",
      logo: "/researcherIcon/avatar.svg",
    },
    {
      id: 4,
      status: "audited",
      title: "New feature implementation",
      priority: "High",
      issueCount: 2,
      description: "Implementation of dark mode feature based on user feedback and requests.",
      deadline: "12th - Nov - 2025",
      submitted: "12th - Nov - 2025",
      action: "Go to Project",
      logo: "/researcherIcon/avatar.svg",
    },
  ]
